-- CreateTable
CREATE TABLE "ConstanciaCalculo" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tipoCC" TEXT NOT NULL,
    "numeroMemoria" TEXT NOT NULL,
    "fecha" DATETIME NOT NULL,
    "nombre" TEXT NOT NULL,
    "direccion" TEXT NOT NULL,
    "medidor" TEXT,
    "tarifa" TEXT,
    "rpu" TEXT,
    "geo" TEXT,
    "agencia" TEXT,
    "descripcion" TEXT NOT NULL,
    "tipoAnomalia" TEXT NOT NULL,
    "tipoGiro" TEXT NOT NULL,
    "metodoCalculo" TEXT NOT NULL,
    "periodoAjuste" TEXT NOT NULL,
    "amperes" TEXT,
    "volts" TEXT,
    "transformadores" TEXT,
    "personaAtiende" TEXT NOT NULL,
    "ordenSuspension" TEXT,
    "evidenciaBase64" TEXT,
    "ingenieroNombre" TEXT NOT NULL DEFAULT 'ING. MIGUEL BRAVO CRUZ',
    "puesto" TEXT NOT NULL DEFAULT 'SUPERVISOR ZONA',
    "area" TEXT NOT NULL DEFAULT 'ÁREA MEDICIÓN MATAMOROS',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
